### ISSUE TITLE
debug build?

### ISSUE THREAD

**Issue by pjz** [blinktrade/frontend#102]
Is there a way to have a 'debug build' of the frontend?  One where, for instance, the javascript isn't compiled into unreadability?   How do you debug the frontend?

**Comment by pinhopro** [comment]
you have to add the following compiler_flags on build_release.js 

--compiler_flags="--debug=TRUE" 
--compiler_flags="--formatting=PRETTY_PRINT" 
--compiler_flags="--formatting=PRINT_INPUT_DELIMITER"

**Comment by pjz** [comment]
Thansk!
