### ISSUE TITLE
Verification page: Firefox NoScript: XSS / clickjacking attempts alerts (caused by Jotform)

### ISSUE THREAD

**Issue by BTCxEagle** [blinktrade/frontend#123]
https://vietnam.blinktrade.com/en_US/#verification 

I receive ongoing alerts about XSS / clickjacking attempts (caused by jotform); see screenshots
     attached.

![screenshot 2015-08-17 19 44 10](https://cloud.githubusercontent.com/assets/13838053/9426868/4cefe8bc-495c-11e5-8052-3a201914b2e2.png)
![screenshot 2015-08-17 19 46 17](https://cloud.githubusercontent.com/assets/13838053/9426869/4d1d9e7e-495c-11e5-8427-4e858976a151.png)

**Comment by pinhopro** [comment]
it is not a problem.
