### ISSUE TITLE
VBTC - Bank account info withdrawal reusability

### ISSUE THREAD

**Issue by BTCxEagle** [blinktrade/frontend#131]
Currently the users has to enter his bank account info every time again, when he is doing a Fiat withdrawal.

---> More effort for the user
---> Higher probability of mistakes = withdrawals will bounce back = additional work

Bank accounts should be reusable in this case.

**Comment by pinhopro** [comment]
will be available in the 4th week of September.

**Comment by ptrinh** [comment]
Is this feature available soon?

Also we want to be able to approve withdrawal info, so that the name for withdrawal must match the verification name

**Comment by pinhopro** [comment]
it is already implemented, but not in production yet.  Should be available in next week
