### ISSUE TITLE
VBTC - change timezone to local (GMT + 7)

### ISSUE THREAD

**Issue by ptrinh** [blinktrade/frontend#132]
VBTC - change timezone to local (GMT + 7)

**Comment by pinhopro** [comment]
where ?

**Comment by ptrinh** [comment]
https://vbtc.exchange/en_US/#account_overview/ptrinh/

--> Last login	2015-09-09 05:14:32. Should be at 12:14:32
Also for Registration date

**Comment by pinhopro** [comment]
the admin panel only shows UTC time.
