### ISSUE TITLE
Changing deposit instruction

### ISSUE THREAD

**Issue by ptrinh** [blinktrade/frontend#144]
This one: https://api.blinktrade.com/get_deposit/?deposit_id=b9e71329b3644632b0cfc959c844a9c4

Could you change this 2 lines:

Viết số kiểm soát (301000185) trong việc nhận tiền gửi
(Write the control number (301000185) in the deposit receipt)

To:

Viết số kiểm soát (301000185) vào nội dung chuyển khoản
(Write the control number (301000185) in the payment details)

**Comment by pinhopro** [comment]
done
