### ISSUE TITLE
Changing deposit status

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#147]
Change "Unconfirmed/Não Confirmado" to "Waiting/Aguardando depósito".

**Comment by pinhopro** [comment]
@cesardeazevedo Alterar este requer alterar somente os arquivos de tradução, e não o código em si.

**Comment by cesardeazevedo** [comment]
Done at https://github.com/cesardeazevedo/frontend/commit/000fe5bb65fa7f86a5eade843ffbfe3ab947a638
