### ISSUE TITLE
Adicionar método de depósito no grid do Admin (Default)

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#151]
Adicionar o método de depósito (banco) no grid do Admin.

Para que não quebre muito o tamanho do grid, colocar um ícone por banco.

Tema: Default.

**Comment by pinhopro** [comment]
Cada método de deposito começa com um número de controle diferenciado. 
401 para caixa, 402 para BB, 403 para Bradesco. 

Colocar um icone para cada banco é algo que requer um esforço muito grande para uma função que é meramente administrativa. 

Fechando o ticket.

**Comment by schiavonxv** [comment]
Qual os números de controle dos outros métodos de depósito? TED e Em dinheiro.
