### ISSUE TITLE
Remover redes sociais no footer (Coinage)

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#153]
Não é necessário ter as redes sociais no footer, acredito que isso só pesa e aumenta o tamanho da página, sem necessidade alguma, pois as mesmas informações estão no Site Institucional.

<img width="1440" alt="captura de tela 2016-04-11 as 20 52 17" src="https://cloud.githubusercontent.com/assets/6706042/14445928/7b2b4618-0027-11e6-966a-32416f4ec3b7.png">

**Comment by pinhopro** [comment]
O Footer é extremamente necessário, principalmente com todas as informações de contato.
