### ISSUE TITLE
Trocar o gráfico da aba Mercado para o TradingView (Todos).

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#154]
O Gráfico da aba mercado não funciona muito bem, além de não ter filtro de data.

Adicionar o gráfico do TradingView no lugar e remover o Link Graphs do footer do tema Coinage.

Não faz sentido eu ter que sair da plataforma para abrir um gráfico.

**Comment by cesardeazevedo** [comment]
Done at https://github.com/cesardeazevedo/frontend/commit/34d066e8f3afc015c119441de01bdc25c85c86ad
