### ISSUE TITLE
Adicionar Meu Perfil no menu lateral (Coinage)

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#155]
Os usuários possuem dificuldades em encontrar acessos/funções escondidas na plataforma.

Por favor, voltar o menu Meu Perfil no menu lateral.

**Comment by cesardeazevedo** [comment]
Done at https://github.com/cesardeazevedo/frontend/commit/1bdc9645fbd1421554d53113116a5c428687d511
