### ISSUE TITLE
Alterações na barra de Status lateral (Coinage)

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#156]
Trocar a mensagem "Tweets by ‎@foxbitstatus" para apenas Status.

<img width="230" alt="captura de tela 2016-04-11 as 21 01 47" src="https://cloud.githubusercontent.com/assets/6706042/14446114/e283412a-0028-11e6-8372-46274e2855ec.png">

Retirar o embed/view on twitter.
<img width="234" alt="captura de tela 2016-04-11 as 21 01 53" src="https://cloud.githubusercontent.com/assets/6706042/14446110/db3671a8-0028-11e6-8c58-a5b8e6cd0beb.png">

**Comment by pinhopro** [comment]
Isso é uma caracteristica do próprio plugin do Twitter. Não tem como alterar/customizar.
