### ISSUE TITLE
Adicionar Motivo de Negação para a Verificação de Cliente (Default)

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#157]
Na verificação de clientes, é necessário ter alguma forma de notificação via email para o cliente saber porque o cadastro dele foi negado, semelhante ao cancelamento de saque/depósito.

Adicionar os seguintes motivos:

Documento de identidade ilegível;
Documento de identidade vencido;
Comprovante de residência vencido;
Comprovante de residência inválido;
Cadastro duplicado;
Menor de 16 anos;

**Comment by pinhopro** [comment]
A negação do cadastro é um evento muito pessoal, e deve ser tratado de forma pessoal. Todas as exchanges que visitamos,  quando ocorre algum tipo de falta de documentação é resolvido por email, via ticket de suporte.

**Comment by schiavonxv** [comment]
Quando se tem poucos casos, OK, concordo, mas o problema é quando isso se torna frequente e ficar criando vários tickets não é escalável.

Se tiver uma forma mais fácil de notificar o cliente, como um Motivo de Cancelamento, ajudaria muito na operação.

**Comment by pinhopro** [comment]
O formulário onde solicitamos os documentos precisam ser melhorados para evitar pedidos incompletos ou com informações inconsistentes.
