### ISSUE TITLE
On the "Create API key" view, clicking "Select all" or "Clear all" doesn't work

### ISSUE THREAD

**Issue by sonofliberty** [blinktrade/frontend#158]
Title says everything.

**Comment by pinhopro** [comment]
@cesardeazevedo Can you please take a look at this?

**Comment by cesardeazevedo** [comment]
It actually never has been implemented, done at https://github.com/pinhopro/pinhopro.github.io/pull/40/commits/e0396748bb615f7817f5f499418d75c4e9ad2110
