### ISSUE TITLE
Não permitir que o usuário reenvie formulário de verificação durante verificação

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#159]
Quando um usuário preenche o formulário de KYC e faz logoff, aparece novamente a mensagem de verificação ao fazer login.

Isso ocasiona o reenvio dos documentos várias vezes durante o prazo de verificação, chegando a 3 ou 4 vezes.

Dica: não mostrar a mensagem novamente ou mostrar alguma mensagem falando que está pendente.

**Comment by cesardeazevedo** [comment]
Isso já foi feito uns 20 dias atrás, https://github.com/cesardeazevedo/frontend/commit/40d49ad3b778ed711b347e956bcd633ccbb90517
