### ISSUE TITLE
Alterar descrição do método de depósito Dinheiro na boca do Caixa/Lotérica

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#161]
Retirar Lotérica do Método de Depósito, deixar somente Dinheiro na boca do caixa

Mudar as instruções:

1. Vá até uma agência da Caixa.
2. Faça um **depósito identificado com seu CPF** na seguinte conta:

Nome do Banco: Caixa Econômica Federal 
Agência: 1205 
Operação: 003 
Número da Conta: 1510-7 
Nome do titular da conta: FoxBit serviços digitais LTDA
CNPJ: 21.246.584/0001-50 

**3. Lembre-se de pedir para identificar seu depósito com seu CPF**
4. Importante: Escreva o número de controle (405002668) no comprovante. 
5. Tire uma foto do comprovante ao lado do seu documento de identificação.
6. Envie o comprovante pelo sistema.
7. Depósitos feitos sem envio o de comprovante não serão confirmadas.

A lotérica tem limite de R$1500, que esgota muito rápido, e muitos usuários vão pra depositar e acabam não podendo, o que causa um mal estar com a FOXBIT.

**Comment by pinhopro** [comment]
done.
