### ISSUE TITLE
Alterar cor do status Pré-Aprovado.

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#173]
Na aba Depósitos, o status Pré-Aprovado está com a cor verde, o que confunde com o status Completado, que também é verde.

**Sugestão**: Alterar para Roxo, para dar um contraste com a cor Verde.

Atualmente:

Cor Cinza: Aguardando depósito;
Cor Laranja: Pendente;
Cor Azul: Em andamento;
Cor Verde: Completado;
Cor Verde: Pré-aprovado;
Cor Vermelho: Cancelado.

**Comment by cesardeazevedo** [comment]
[https://github.com/cesardeazevedo/frontend/commit/db2256b50ba7fddeaa3e335d499d7fa4e094615b](https://github.com/cesardeazevedo/frontend/commit/db2256b50ba7fddeaa3e335d499d7fa4e094615b)

**Comment by pinhopro** [comment]
@cesardeazevedo , vc trocou a cor do botão e não do "label" que aparece.

**Comment by cesardeazevedo** [comment]
revert - https://github.com/pinhopro/pinhopro.github.io/commit/704482dd0a617f24e9ff0acf4aa857983b6f6a9a
