### ISSUE TITLE
Alterar paginação 

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#174]
Na última atualização, a paginação passou a ser 20 itens por página, mas isso é ruim e dificulta as operações de administrador.

Alterar para, no mínimo, 50 itens.

**Comment by pinhopro** [comment]
Foi alterado para 20 por questões de performance.

**Comment by pinhopro** [comment]
Será incluído um filtro para o tipo de métodos de deposito/saque escolhido.
