### ISSUE TITLE
Alterar a cor do fundo de saques conforme o estado

### ISSUE THREAD

**Issue by felipetdsa** [blinktrade/frontend#175]
Saques completados ficarem com o fundo verde.
Saques pendentes com fundo braco.
Saques em andamento com fundo amarelo

**Comment by cesardeazevedo** [comment]
Olá Felipe, não entendi muito bem.

A label do status não seria o suficiente?
![screen shot 2016-05-25 at 21 48 06](https://cloud.githubusercontent.com/assets/5366959/15560485/678e368e-22c2-11e6-8012-255103daff02.png)

**Comment by pinhopro** [comment]
Acho que fica mais fácil de mudar a cora da linha inteira.  

Tem como fazer isso somente no módulo de admin no tema simples ?
