### ISSUE TITLE
Alterar "Nome de usuário" na tela de Registro

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#180]
Na tela de registro, os usuários confundem "**Nome de Usuário**" com "**Nome Completo**", causando um número de tickets desnecessários.

Sugiro alterar para Login, pois ai não dá pra confundir com Nome.

**Comment by pinhopro** [comment]
@cesardeazevedo. Isso é na tela de signup.....  Acho que é só trocar o arquivo de tradução do jekyll.

**Comment by schiavonxv** [comment]
Ok.
Isso está gerando cerca de 5% dos tickets diários.

**Comment by schiavonxv** [comment]
Podem me passar o arquivo de tradução?

**Comment by pinhopro** [comment]
Alterado para Nickname
