### ISSUE TITLE
Exclusão lógica

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#182]
Alguns clientes pedem para ter a conta/documentos excluídos da plataforma.
Como devemos manter registros, não podemos excluir do banco de dados, mas o cliente ainda insiste em excluir.

Hoje eu tenho que logar na conta da pessoa e ativar 2FA, para que ela veja que a conta foi bloqueada. Isso leva tempo.

Sugestão: Ter um botão de exclusão lógica no perfil do cliente no Admin, onde, depois de tentar logar, a pessoa veria que a conta foi excluida... ou um botão pra ativar 2FA.

**Comment by pinhopro** [comment]
Ja estamos fazendo botão de bloquear a conta automaticamente.
