### ISSUE TITLE
Alterar mensagem após envio dos documentos

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#184]
**Mensagem atual:**

Obrigado!

Sua conta será verificada em breve

**Trocar para:** 

Obrigado!

Sua conta será verificada em até 24h úteis.

**Motivo:** muita gente envia os documentos e 10 minutos dps manda ticket perguntando o prazo.

**Comment by pinhopro** [comment]
Alterado para:

Obrigado!
Sua conta será verificada dentro do prazo de 1 dia útil.
