### ISSUE TITLE
Alterar mensagem nos métodos de depósito.

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#186]
**Banco do Brasil**, alterar para:

Disponível apenas para transferência bancária entre contas do Banco do Brasil de mesmo titular. É EXPRESSAMENTE PROIBIDO realizar depósitos em dinheiro na boca do caixa, sujeito a multa de 2% no valor do depósito. Transferências serão confirmadas em média em 30 minutos, com prazo de até 24h. Para AGILIZAR a identificação da transferência, utilize centavos no valor transferido. Ex: R$ 2000,14. Horário de Funcionamento: Seg a Sexta - 9h às 19h. 

**Bradesco**, alterar para:

Disponível apenas para transferência bancária entre contas do Bradesco de mesmo titular. É EXPRESSAMENTE PROIBIDO realizar depósitos em dinheiro na boca do caixa, sujeito a multa de 2% no valor do depósito. Transferências serão confirmadas em média em 60 minutos, com prazo de até 24h. Para AGILIZAR a identificação da transferência, utilize centavos no valor transferido. Ex: R$ 2000,14. Horário de Funcionamento: Seg a Sexta - 9h às 19h. 

**Caixa**, alterar para:

Disponível apenas para transferência bancária entre contas da Caixa de mesmo titular. É EXPRESSAMENTE PROIBIDO realizar depósitos em dinheiro na boca do caixa SEM IDENTIFICAÇÃO, sujeito a multa de 2% no valor do depósito. Transferências serão confirmadas em média em 60 minutos, com prazo de até 24h. Para AGILIZAR a identificação da transferência, utilize centavos no valor transferido. Ex: R$ 2000,14. Horário de Funcionamento: Seg a Sexta - 9h às 19h. 
 
**Outros Bancos**, alterar para:

Disponível apenas para transferência via TED/DOC. É EXPRESSAMENTE PROIBIDO realizar transferências de contas com CPF diferente do cadastrado no sistema. TEDs realizados em horário comercial serão confirmados em média em 60 minutos, já DOCs são processados pelo banco em média em 24 horas. Para AGILIZAR a identificação da transferência, utilize centavos no valo. Ex: R$ 2000,14. Horário de Funcionamento: Seg a Sexta - 9h às 19h.

**Comment by pinhopro** [comment]
Todos feitos. 

Apesar de no pedido do banco do brasil vc ter colocado tempo médio de 30 minutos, eu realizei a mudança para 60 minutos.
