### ISSUE TITLE
Alterar máximo para disponível na tela de saques.

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#188]
Usuários estão reclamando que a mensagem Mínimo/Maximo na tela de saques está errada ou confusa.

De fato, se mudar o **Máximo** para **Disponível**, pode ser que faça mais sentido.

**Disponível**: o que ele pode sacar;
**Mínimo**: o que o sistema aceita sacar;

Imagem: https://foxbit.zendesk.com/attachments/token/mcJzrHosk6p56jNkvkFPuJa5w/?name=foxbit.PNG

Se possível, colocar o quebra de linha depois do valor do Máximo/Disponível, pra ficar abaixo do Mínimo. Ficaria mais bonito.

**-----------**

O melhor cenário seria colocar:

**Disponível**: o que ele pode sacar;
**Mínimo**: o mínimo que ele pode sacar;
**Máximo**: o máximo que ele pode sacar conforme o nível;

Se não for possível fazer esse **melhor cenário** agora, pelo menos alterar **Máximo** para **Disponível**.

**Comment by pinhopro** [comment]
@cesardeazevedo , alterar de "Máximo" para "Max Disponível"

**Comment by cesardeazevedo** [comment]
https://github.com/cesardeazevedo/frontend/commit/826968e76d264ac1288fe3ee9c3b8fc7c2843a5a
