### ISSUE TITLE
Alterar métodos de saque

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#189]
No método **Outros Bancos**, alterar para:

Saques solicitados até as 16:30h serão realizados em média em 60 minutos após solicitação. Não realizamos saque em reais para conta com CPF/CNPJ diferente do que está registrado na FoxBIT, exceto para pai e mãe contidos no documento com foto. Horário de Funcionamento: Seg a Sexta - 9h às 19h.

No método **BB**, alterar para:

Os saques serão realizados em média em 30 minutos e, em casos excepcionais, poderão ser realizados em até 24 horas úteis. Não realizamos saque em reais para conta com CPF/CNPJ diferente do que está registrado na FoxBIT, exceto para pai e mãe contidos no documento com foto. Horário de Funcionamento: Seg a Sexta - 9h às 19h.

No método **Caixa**, alterar para:

Devido a restrições da Caixa, o primeiro saque precisa de liberação da nossa gerência, o que é realizado entre 10 e 16h do horário de Brasília. Os saques serão realizados em média em 30 minutos durante horário comercial e, em casos excepcionais, poderão ser realizados em até 24 horas úteis. Não realizamos saque em reais para conta com CPF/CNPJ diferente do que está registrado na FoxBIT, exceto para pai e mãe contidos no documento com foto. Horário de Funcionamento: Seg a Sexta - 9h às 19h.

No método **Bradesco**, alterar para:

Os saques serão realizados em média em 30 minutos e, em casos excepcionais, poderão ser realizados em até 24 horas úteis. Não realizamos saque em reais para conta com CPF/CNPJ diferente do que está registrado na FoxBIT, exceto para pai e mãe contidos no documento com foto. Horário de Funcionamento: Seg a Sexta - 9h às 19h.

**Comment by pinhopro** [comment]
Todos as descrições dos saques podem ser alteradas diretamente no painel administrativo de métodos de saque.
