### ISSUE TITLE
Alterações na página Sobre a Exchange

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#190]
Na tabela de taxas, adicionar o **link** https://foxbit.com.br/taxas#execucaoOrdem nos **Termos** da Taxa de Trade.

Alterar o custo o **Custo para outros bancos** para 1,39% + R$ 8,25

Tornar os endereços da FOXBIT **não copiáveis** ou adicionar uma mensagem que **não é permitido depositar nesses endereços**. Muitos usuários depositam nos endereços hot e cold.

**Comment by pinhopro** [comment]
Esta informação é montada de forma dinâmica e requer deploy de nova versão.

@cesardeazevedo , tem como colocar os endereços que aparecem na carteiras como "não selecionaveis"  e retirar o link ?

**Comment by cesardeazevedo** [comment]
https://github.com/cesardeazevedo/frontend/commit/d7510ad36d793d4f45192f447390ae30c305ecfb
