### ISSUE TITLE
Melhorar Pesquisa por nome de cliente

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#192]
Hoje o nome é dividido em 3 partes, primeiro, do meio e sobrenome.

Na hora da pesquisa, isso não é muito funcional, pois se o cliente chamar **Rodrigo Silva Pereira**, eu não consigo pesquisar por Rodrigo Silva, somente por Rodrigo ou Silva ou Pereira, ficando impossível de encontrar.

**Comment by pinhopro** [comment]
Consegue sim .... é tão óbvio que eu não sei o como você não saiba :P 

"last": "Pereira"
procura por todo mundo com último nome Pereira

ou 
"middle": "Silva"
procura por todo mundo com nome do meio Silva


ou 
"first": "Rodrigo"
procura por todo mundo com primeiro nome Rodrigo

ou 
"middle": "Silva", "last": "Pereira"
procura por todo mundo com nome do meio "Silva" e ultimo nome "Pereira"

ou 
"last": "Silva", "first": "Rodrigo"
procura por todo mundo com ultimo nome  "Pereira" e primeiro nome "Rodrigo"

**Comment by schiavonxv** [comment]
Até sabia sim, deduzi pelo verification_data, mas convenhamos que é fod* procurar por "last": "Silva", "first": "Rodrigo" né rs
