### ISSUE TITLE
Adicionar método de saque e depósitos

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#194]
Adicionar método de Saque e Depósito Sicredi.

Dados da conta: Sicredi Ag: 0726 Cc: 42247-7.

Instrução pra **depósito**:

Disponível apenas para transferência bancária entre contas do Banco do Brasil de mesmo titular. É EXPRESSAMENTE PROIBIDO realizar depósitos em dinheiro na boca do caixa, sujeito a multa de 2% no valor do depósito. Transferências serão confirmados em média em 60 minutos. Horário de Funcionamento: Seg a Sexta - 9h às 19h.

Instrução pra **saque**:

Os saques serão realizados em média em 30 minutos e, em casos excepcionais, poderão ser realizados em até 24 horas úteis. Não realizamos saque em reais para conta com CPF/CNPJ diferente do que está registrado na FoxBIT, exceto para pai e mãe contidos no documento com foto. Horário de Funcionamento: Seg a Sexta - 9h às 19h.

**Comment by pinhopro** [comment]
Para saque você mesmo tem acesso para realizar.
