### ISSUE TITLE
Retirar Estado do Meu Perfil ou permitir alteração 

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#195]
Alguns usuários respondem errado o estado, ai enviam ticket para alterar. Como não podemos alterar, fico de mãos atadas.

Retirar o **Estado** do Meu Perfil ou permitir que nós ou os usuários alterem.

**Comment by pinhopro** [comment]
Será permitida a alteração. Prioridade baixa.

@cesardeazevedo, vc sabe como fazer né?

**Comment by pinhopro** [comment]
Por enquanto, retire o país e estado.  

Na próxima versão, será permitida a alteração.

**Comment by cesardeazevedo** [comment]
https://github.com/cesardeazevedo/frontend/commit/6a20cdcc1232405312178d87b274c97128739048
