### ISSUE TITLE
Alterar widget do Zopim (Prioridade).

### ISSUE THREAD

**Issue by schiavonxv** [blinktrade/frontend#196]
Alterar o código da lateral do widget do Zopim.

O código abaixo é do Zendesk, ele vai tirar o chat, mas vai adicionar uma central de ajuda e ainda sim permitir mensagem, mas o usuário vai primeiro pesquisar pra ver se a dúvida não foi respondida.

```
<!-- Start of foxbit Zendesk Widget script -->
<script>/*<![CDATA[*/window.zEmbed||function(e,t){var n,o,d,i,s,a=[],r=document.createElement("iframe");window.zEmbed=function(){a.push(arguments)},window.zE=window.zE||window.zEmbed,r.src="javascript:false",r.title="",r.role="presentation",(r.frameElement||r).style.cssText="display: none",d=document.getElementsByTagName("script"),d=d[d.length-1],d.parentNode.insertBefore(r,d),i=r.contentWindow,s=i.document;try{o=s}catch(c){n=document.domain,r.src='javascript:var d=document.open();d.domain="'+n+'";void(0);',o=s}o.open()._l=function(){var o=this.createElement("script");n&&(this.domain=n),o.id="js-iframe-async",o.src=e,this.t=+new Date,this.zendeskHost=t,this.zEQueue=a,this.body.appendChild(o)},o.write('<body onload="document._l();">'),o.close()}("https://assets.zendesk.com/embeddable_framework/main.js","foxbit.zendesk.com");
/*]]>*/</script>
<!-- End of foxbit Zendesk Widget script -->

```

ISSO é PRIORIDADE.

**Comment by pinhopro** [comment]
Eu troquei de forma emergencial, mas creio que chat ao vivo é muito mais eficiente do que um sistema de ticket de suporte.

E forçar o usuário a ler as dúvidas já respondidas vai frustar o usuário, que deseja uma resposta rápida para o problema dele.

**Comment by schiavonxv** [comment]
Eu até concordo, mas no momento não estamos com capacidade para atender o chat online.
Em breve voltaremos com ele.
