### ISSUE TITLE
Problemas com o form de compra/venda no Livro Contabil

### ISSUE THREAD

**Issue by jpereira** [blinktrade/frontend#204]
Simplesmente desaparece. percebi que ele fica hidden e depois não aparece novamente sendo preciso sair e entrar de novo. péssimo comportamento.
![screenshot from 2016-06-26 16-48-49](https://cloud.githubusercontent.com/assets/254448/16364486/71f3e60e-3bbe-11e6-970f-458572aee137.png)

**Comment by jpereira** [comment]
Utilizo Linux + Chrome (latest)

**Comment by pinhopro** [comment]
Quais são os passos para repetir este comportamento?

**Comment by jpereira** [comment]
@pinhopro não recordo os passos. mais percebi que quando tem alguma lentidão o evento que manipula o show/hidden daquele div simplesmente coloca em hidden e não volta mais.
