### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeItem' of undefined

### ISSUE THREAD

**Issue by jpereira** [blinktrade/frontend#212]
![foxbit-bug2](https://cloud.githubusercontent.com/assets/254448/16738417/f18a9d96-476b-11e6-903b-697696085729.png)

**Comment by pinhopro** [comment]
Tem alguma instrução sobre como reproduzir este bug? 

Quais passos você executou antes?

**Comment by jpereira** [comment]
@pinhopro ah! Muito tempo, não recordo mais... acho que foi após autenticar em browsers diferente, não estou 100% certo!
