### ISSUE TITLE
tela "Histório de Ordem" exibe valores errado.

### ISSUE THREAD

**Issue by jpereira** [blinktrade/frontend#215]
Pessoal,

Algum problema com a mascara que exibe os valores.

![image](https://cloud.githubusercontent.com/assets/254448/17345220/6646f442-58db-11e6-9726-b5c154495091.png)

**Comment by pinhopro** [comment]
Qual valor que está errado?

**Comment by jpereira** [comment]
o total zerado?

**Comment by pinhopro** [comment]
O total é o total executado. Neste caso da imagem, não houve nenhuma execução, portanto o total de R$ 0,00 foi executado.  

Talvez seja melhor trocar o texto.

**Comment by jpereira** [comment]
ah! saquei @pinhopro. realmente para uma melhor usabilidade talvez seja melhor trocar o texto ou por o campo com outra cor e uma legenda... ou mais uma coluna "executado / não executado"... enfim, fica sugestão.
