### ISSUE TITLE
Footer: API href is empty

### ISSUE THREAD

**Issue by sonofliberty** [blinktrade/frontend#232]
frontend/_includes/footer.coinage.html:54

**Comment by cesardeazevedo** [comment]
Hi Alex, thanks for report.

The navigation href are handled by the `data-switch-view` property.
but indeed, the API link will only work when you are actually logged, this is something that will be fixed soon.

**Comment by sonofliberty** [comment]
Ah, I see. Yes I wasn't logged in and tried to click on the link.
Thank you!
