### ISSUE TITLE
Help with frontend

### ISSUE THREAD

**Issue by juniorth6** [blinktrade/frontend#75]
I would love to contribute to the project, and am having some trouble running the project locally, I get the following error.

Pro-de-Isaias:exchange isaiasantunes$ jekyll server --watch
Configuration file: none
            Source: /Users/isaiasantunes/exchange
       Destination: /Users/isaiasantunes/exchange/_site
 Incremental build: enabled
      Generating...
jekyll 3.0.0-beta1 | Error:  undefined method `first' for nil:NilClass

**Comment by cesardeazevedo** [comment]
Probably you forgot to set your configuration file (_config.yml), there is a lot of them of each exchange, _config.foxbit.yml,  _config.romaniabex.yml, _config.demo.yml, i recommend that you create a symbolic link to _config.demo.yml. you can do this easy with command: 

`ln -s _config.demo.yml _config.yml`
